name: Read MSRV

on:
  workflow_call:
    outputs:
      msrv:
        value: ${{ jobs.read_msrv.outputs.msrv }}

permissions:
  contents: read

jobs:
  read_msrv:
    name: Read MSRV

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Rust (stable)
        uses: actions-rust-lang/setup-rust-toolchain@ecabd13d1c56bd1345c230e542e9144811ad706f # v2.0.0
        inputs:
          build-warnings: false
          cache: false
          matcher: false

      - name: Read MSRV from workspace manifest
        id: read_msrv
        run: |
          cargo metadata --format-version=1 \
          | jq -r 'first(.packages[] | select(.source == null and .rust_version)) | .rust_version' \
          | sed -E 's/^1\.([0-9]{2})$/1\.\1\.0/' \
          | xargs -0 printf "msrv=%s" \
          | tee /dev/stderr \
          >> "$GITHUB_OUTPUT"

    outputs:
      msrv: ${{ steps.read_msrv.outputs.msrv }}
