name: Read MSRV

on:
  workflow_call:
    outputs:
      msrv:
        value: ${{ jobs.read_msrv.outputs.msrv }}

permissions:
  contents: read

jobs:
  read_msrv:
    name: Read MSRV

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: actions-rust-lang/setup-rust-toolchain@v1.8.0

      - name: Read MSRV from workspace manifest
        id: read_msrv
        run: |
          cargo metadata --format-version=1 \
          | jq -r 'first(.packages[] | select(.source == null and .rust_version)) | .rust_version' \
          | sed -E 's/^1\.([0-9]{2})$/1\.\1\.0/' \
          | xargs -0 printf "msrv=%s" \
          | tee /dev/stderr \
          >> "$GITHUB_OUTPUT"

    outputs:
      msrv: ${{ steps.read_msrv.outputs.msrv }}
